# fly.toml app configuration file generated for node-geodaily on 2023-09-20T17:32:28+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "node-geodaily"
primary_region = "lhr"

[deploy]
release_command = "npx prisma migrate deploy"

[env]
  ACCESS_TOKEN_SECRET="PRs8YA989iXTFKYmmHTTLs7EoDtwA2engEEqjpsp"
  REFRESH_TOKEN_SECRET="3drnBaHadYbWdQQqGLWJ6NVB5JxuD4m5qf5qLfHa"
  MAPS_API_KEY="AIzaSyDxqLKY4EP8XPu9rvsz2iTpjJc4mQCk3po"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
